/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as R404RouteImport } from './routes/404'
import { Route as JaRouteImport } from './routes/ja'
import { Route as NewRouteImport } from './routes/new'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as JaIndexRouteImport } from './routes/ja.index'
import { Route as JaSlugRouteImport } from './routes/ja.$slug'
import { Route as Ja404RouteImport } from './routes/ja.404'
import { Route as JaNewRouteImport } from './routes/ja.new'
import { Route as JaSearchRouteImport } from './routes/ja.search'
import { Route as JaCategoryCategoryRouteImport } from './routes/ja.category.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const JaRoute = JaRouteImport.update({
  id: '/ja',
  path: '/ja',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const JaIndexRoute = JaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JaRoute,
} as any)
const JaSlugRoute = JaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JaRoute,
} as any)
const Ja404Route = Ja404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => JaRoute,
} as any)
const JaNewRoute = JaNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JaRoute,
} as any)
const JaSearchRoute = JaSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => JaRoute,
} as any)
const JaCategoryCategoryRoute = JaCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => JaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/ja': typeof JaRouteWithChildren
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/ja/$slug': typeof JaSlugRoute
  '/ja/404': typeof Ja404Route
  '/ja/new': typeof JaNewRoute
  '/ja/search': typeof JaSearchRoute
  '/ja/': typeof JaIndexRoute
  '/ja/category/$category': typeof JaCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/ja/$slug': typeof JaSlugRoute
  '/ja/404': typeof Ja404Route
  '/ja/new': typeof JaNewRoute
  '/ja/search': typeof JaSearchRoute
  '/ja': typeof JaIndexRoute
  '/ja/category/$category': typeof JaCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/ja': typeof JaRouteWithChildren
  '/new': typeof NewRoute
  '/search': typeof SearchRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/ja/$slug': typeof JaSlugRoute
  '/ja/404': typeof Ja404Route
  '/ja/new': typeof JaNewRoute
  '/ja/search': typeof JaSearchRoute
  '/ja/': typeof JaIndexRoute
  '/ja/category/$category': typeof JaCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/404'
    | '/ja'
    | '/new'
    | '/search'
    | '/category/$category'
    | '/ja/$slug'
    | '/ja/404'
    | '/ja/new'
    | '/ja/search'
    | '/ja/'
    | '/ja/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/404'
    | '/new'
    | '/search'
    | '/category/$category'
    | '/ja/$slug'
    | '/ja/404'
    | '/ja/new'
    | '/ja/search'
    | '/ja'
    | '/ja/category/$category'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/404'
    | '/ja'
    | '/new'
    | '/search'
    | '/category/$category'
    | '/ja/$slug'
    | '/ja/404'
    | '/ja/new'
    | '/ja/search'
    | '/ja/'
    | '/ja/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  R404Route: typeof R404Route
  JaRoute: typeof JaRouteWithChildren
  NewRoute: typeof NewRoute
  SearchRoute: typeof SearchRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja': {
      id: '/ja'
      path: '/ja'
      fullPath: '/ja'
      preLoaderRoute: typeof JaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/': {
      id: '/ja/'
      path: '/'
      fullPath: '/ja/'
      preLoaderRoute: typeof JaIndexRouteImport
      parentRoute: typeof JaRoute
    }
    '/ja/$slug': {
      id: '/ja/$slug'
      path: '/$slug'
      fullPath: '/ja/$slug'
      preLoaderRoute: typeof JaSlugRouteImport
      parentRoute: typeof JaRoute
    }
    '/ja/404': {
      id: '/ja/404'
      path: '/404'
      fullPath: '/ja/404'
      preLoaderRoute: typeof Ja404RouteImport
      parentRoute: typeof JaRoute
    }
    '/ja/new': {
      id: '/ja/new'
      path: '/new'
      fullPath: '/ja/new'
      preLoaderRoute: typeof JaNewRouteImport
      parentRoute: typeof JaRoute
    }
    '/ja/search': {
      id: '/ja/search'
      path: '/search'
      fullPath: '/ja/search'
      preLoaderRoute: typeof JaSearchRouteImport
      parentRoute: typeof JaRoute
    }
    '/ja/category/$category': {
      id: '/ja/category/$category'
      path: '/category/$category'
      fullPath: '/ja/category/$category'
      preLoaderRoute: typeof JaCategoryCategoryRouteImport
      parentRoute: typeof JaRoute
    }
  }
}

interface JaRouteChildren {
  JaSlugRoute: typeof JaSlugRoute
  Ja404Route: typeof Ja404Route
  JaNewRoute: typeof JaNewRoute
  JaSearchRoute: typeof JaSearchRoute
  JaIndexRoute: typeof JaIndexRoute
  JaCategoryCategoryRoute: typeof JaCategoryCategoryRoute
}

const JaRouteChildren: JaRouteChildren = {
  JaSlugRoute: JaSlugRoute,
  Ja404Route: Ja404Route,
  JaNewRoute: JaNewRoute,
  JaSearchRoute: JaSearchRoute,
  JaIndexRoute: JaIndexRoute,
  JaCategoryCategoryRoute: JaCategoryCategoryRoute,
}

const JaRouteWithChildren = JaRoute._addFileChildren(JaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  R404Route: R404Route,
  JaRoute: JaRouteWithChildren,
  NewRoute: NewRoute,
  SearchRoute: SearchRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
