/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LangChar125RouteImport } from './routes/{-$lang}'
import { Route as Char123LangChar125IndexRouteImport } from './routes/{-$lang}.index'
import { Route as Char123LangChar125404RouteImport } from './routes/{-$lang}.404'
import { Route as Char123LangChar125SearchRouteImport } from './routes/{-$lang}.search'
import { Route as Char123LangChar125AppsSlugRouteImport } from './routes/{-$lang}.apps.$slug'
import { Route as Char123LangChar125CategoryCategoryRouteImport } from './routes/{-$lang}.category.$category'

const Char123LangChar125Route = Char123LangChar125RouteImport.update({
  id: '/{-$lang}',
  path: '/{-$lang}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LangChar125IndexRoute = Char123LangChar125IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125404Route = Char123LangChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LangChar125Route,
} as any)
const Char123LangChar125SearchRoute =
  Char123LangChar125SearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125AppsSlugRoute =
  Char123LangChar125AppsSlugRouteImport.update({
    id: '/apps/$slug',
    path: '/apps/$slug',
    getParentRoute: () => Char123LangChar125Route,
  } as any)
const Char123LangChar125CategoryCategoryRoute =
  Char123LangChar125CategoryCategoryRouteImport.update({
    id: '/category/$category',
    path: '/category/$category',
    getParentRoute: () => Char123LangChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/{-$lang}/404': typeof Char123LangChar125404Route
  '/{-$lang}/search': typeof Char123LangChar125SearchRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/apps/$slug': typeof Char123LangChar125AppsSlugRoute
  '/{-$lang}/category/$category': typeof Char123LangChar125CategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/{-$lang}/404': typeof Char123LangChar125404Route
  '/{-$lang}/search': typeof Char123LangChar125SearchRoute
  '/{-$lang}': typeof Char123LangChar125IndexRoute
  '/{-$lang}/apps/$slug': typeof Char123LangChar125AppsSlugRoute
  '/{-$lang}/category/$category': typeof Char123LangChar125CategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$lang}': typeof Char123LangChar125RouteWithChildren
  '/{-$lang}/404': typeof Char123LangChar125404Route
  '/{-$lang}/search': typeof Char123LangChar125SearchRoute
  '/{-$lang}/': typeof Char123LangChar125IndexRoute
  '/{-$lang}/apps/$slug': typeof Char123LangChar125AppsSlugRoute
  '/{-$lang}/category/$category': typeof Char123LangChar125CategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$lang}'
    | '/{-$lang}/404'
    | '/{-$lang}/search'
    | '/{-$lang}/'
    | '/{-$lang}/apps/$slug'
    | '/{-$lang}/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$lang}/404'
    | '/{-$lang}/search'
    | '/{-$lang}'
    | '/{-$lang}/apps/$slug'
    | '/{-$lang}/category/$category'
  id:
    | '__root__'
    | '/{-$lang}'
    | '/{-$lang}/404'
    | '/{-$lang}/search'
    | '/{-$lang}/'
    | '/{-$lang}/apps/$slug'
    | '/{-$lang}/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LangChar125Route: typeof Char123LangChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$lang}': {
      id: '/{-$lang}'
      path: '/{-$lang}'
      fullPath: '/{-$lang}'
      preLoaderRoute: typeof Char123LangChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$lang}/': {
      id: '/{-$lang}/'
      path: '/'
      fullPath: '/{-$lang}/'
      preLoaderRoute: typeof Char123LangChar125IndexRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/404': {
      id: '/{-$lang}/404'
      path: '/404'
      fullPath: '/{-$lang}/404'
      preLoaderRoute: typeof Char123LangChar125404RouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/search': {
      id: '/{-$lang}/search'
      path: '/search'
      fullPath: '/{-$lang}/search'
      preLoaderRoute: typeof Char123LangChar125SearchRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/apps/$slug': {
      id: '/{-$lang}/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/{-$lang}/apps/$slug'
      preLoaderRoute: typeof Char123LangChar125AppsSlugRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
    '/{-$lang}/category/$category': {
      id: '/{-$lang}/category/$category'
      path: '/category/$category'
      fullPath: '/{-$lang}/category/$category'
      preLoaderRoute: typeof Char123LangChar125CategoryCategoryRouteImport
      parentRoute: typeof Char123LangChar125Route
    }
  }
}

interface Char123LangChar125RouteChildren {
  Char123LangChar125404Route: typeof Char123LangChar125404Route
  Char123LangChar125SearchRoute: typeof Char123LangChar125SearchRoute
  Char123LangChar125IndexRoute: typeof Char123LangChar125IndexRoute
  Char123LangChar125AppsSlugRoute: typeof Char123LangChar125AppsSlugRoute
  Char123LangChar125CategoryCategoryRoute: typeof Char123LangChar125CategoryCategoryRoute
}

const Char123LangChar125RouteChildren: Char123LangChar125RouteChildren = {
  Char123LangChar125404Route: Char123LangChar125404Route,
  Char123LangChar125SearchRoute: Char123LangChar125SearchRoute,
  Char123LangChar125IndexRoute: Char123LangChar125IndexRoute,
  Char123LangChar125AppsSlugRoute: Char123LangChar125AppsSlugRoute,
  Char123LangChar125CategoryCategoryRoute:
    Char123LangChar125CategoryCategoryRoute,
}

const Char123LangChar125RouteWithChildren =
  Char123LangChar125Route._addFileChildren(Char123LangChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LangChar125Route: Char123LangChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
